export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const ADD_PLAYER_TO_TEAM = 'ADD_PLAYER_TO_TEAM';
export const DELETE_PLAYER_FROM_TEAM = 'DELETE_PLAYER_FROM_TEAM';
